{% set version = '0.1.4' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fuzzyjoin
  version: {{ version|replace("-", "_") }}

source:
  fn: fuzzyjoin_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/fuzzyjoin_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/fuzzyjoin/fuzzyjoin_{{ version }}.tar.gz
  sha256: 8a0b46b352ced9ad802411f8ad1123bfb510078f0e974da964dd30a8e100211b

build:
  noarch: generic
  number: 1002
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-dplyr
    - r-geosphere
    - r-purrr
    - r-stringdist
    - r-stringr
    - r-tidyr >=0.4.0
  run:
    - r-base
    - r-dplyr
    - r-geosphere
    - r-purrr
    - r-stringdist
    - r-stringr
    - r-tidyr >=0.4.0

test:
  commands:
    - $R -e "library('fuzzyjoin')"  # [not win]
    - "\"%R%\" -e \"library('fuzzyjoin')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=fuzzyjoin
  license: MIT
  summary: Join tables together based not on whether columns match exactly, but whether they
    are similar by some comparison. Implementations include string distance and regular
    expression matching.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
