{% set version = "0.1.8" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-fuzzyjoin
  version: {{ version|replace("-", "_") }}

source:
  fn: fuzzyjoin_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/fuzzyjoin_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/fuzzyjoin/fuzzyjoin_{{ version }}.tar.gz
  sha256: 2af0e9f9641a8ddae4ec9849699410b2e339c2cef73c68b334b837ae9b997a34

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-dplyr
    - r-geosphere
    - r-purrr
    - r-stringdist
    - r-stringr
    - r-tidyr >=0.4.0
  run:
    - r-base
    - r-dplyr
    - r-geosphere
    - r-purrr
    - r-stringdist
    - r-stringr
    - r-tidyr >=0.4.0

test:
  commands:
    - $R -e "library('fuzzyjoin')"  # [not win]
    - "\"%R%\" -e \"library('fuzzyjoin')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=fuzzyjoin
  license: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
  summary: Join tables together based not on whether columns match exactly, but whether they are similar by some comparison. Implementations include string distance and regular expression matching.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
